parameters:
#    mrmiles_content.example.class: mrmiles\ContentBundle\Example

services:
#    mrmiles_content.example:
#        class: %mrmiles_content.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
